const {chromium}=require('/Users/y/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core');
const {spawn,execFileSync}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),python='/Users/y/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
(async()=>{
const data=fs.mkdtempSync(path.join(os.tmpdir(),'syp-creative-')),evidence=process.argv[2]||'/tmp/syp-creative-evidence';fs.mkdirSync(evidence,{recursive:true});
const server=spawn(python,['-u','-c',"from server import make_server;from backend.providers import Gateway;import sys;s=make_server(0,sys.argv[1],Gateway());print(s.server_port,flush=True);s.serve_forever()",data],{cwd:root});
const port=await new Promise((res,rej)=>{server.stdout.once('data',d=>res(Number(d.toString().trim())));server.once('exit',c=>rej(new Error('server '+c)));server.stderr.on('data',d=>process.stderr.write(d));});
let browser;const results=[],errors=[];let external=0;const url='http://127.0.0.1:'+port;
try{
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());page.on('request',r=>{if(!r.url().startsWith(url)&&!r.url().startsWith('blob:'))external++});
 await page.goto(url);await page.locator('#story').waitFor();const token=(await context.cookies()).find(c=>c.name==='syp_session').value;
 const seed=JSON.parse(execFileSync(python,['scripts/seed_creative.py'],{cwd:root,input:JSON.stringify({data_dir:data,session_token:token}),encoding:'utf8'}));
 await page.getByRole('button',{name:'我的小歌',exact:true}).click();await page.getByRole('button',{name:'原声与版本 · 合成音频验收专用',exact:true}).click();await page.locator('[data-action="tap-beat"]').waitFor();
 // A monotonic controlled clock makes the browser input deterministic, not a real participant rhythm.
 await page.evaluate(()=>{let time=10000;performance.now=()=>{time+=500;return time;};});
 for(let i=0;i<4;i++)await page.locator('[data-action="tap-beat"]').click();await page.locator('#tap-status').filter({hasText:'120 BPM'}).waitFor();
 await page.getByRole('button',{name:'重新拍',exact:true}).click();await page.locator('[data-action="tap-beat"]').focus();for(let i=0;i<4;i++)await page.keyboard.press('Space');await page.locator('#tap-status').filter({hasText:'120 BPM · 4 下'}).waitFor();results.push({check:'keyboard_taps_keep_focus',passed:true});
 await page.getByRole('button',{name:'保存这次节奏',exact:true}).click();await page.locator('.rhythm-panel .micro-note').filter({hasText:'120 BPM'}).waitFor();results.push({check:'tap_120_bpm_saved_and_rendered',passed:true,method:'controlled clock'});
 await page.getByRole('button',{name:'试听节拍',exact:true}).click();await page.getByRole('button',{name:'停止节拍',exact:true}).waitFor();await page.getByRole('button',{name:'停止节拍',exact:true}).click();results.push({check:'local_metronome_user_started_and_stopped',passed:true});
 await page.getByRole('button',{name:'原话 / 版本对照试听',exact:true}).first().click();await page.locator('#origin-quote').fill('别急我在呢');await page.getByRole('button',{name:'保存原话关联',exact:true}).click();await page.getByRole('button',{name:'原话 / 版本对照试听',exact:true}).first().click();
 await page.locator('#dialog-content').filter({hasText:'由你明确关联'}).waitFor();assert.equal(await page.locator('#comparison-audio-left blockquote').textContent(),'别急我在呢');assert.match(await page.locator('#comparison-audio-right blockquote').textContent(),/今天陪你走/);
 const before=page.locator('#comparison-audio-left audio').first(),after=page.locator('#comparison-audio-right audio').first();await before.evaluate(a=>a.play());await after.evaluate(a=>a.play());assert.equal(await before.evaluate(a=>a.paused),true);assert.equal(await after.evaluate(a=>a.paused),false);results.push({check:'stable_line_origin_versions_audio_switch_pauses_previous',passed:true,source:'synthetic tones'});
 await page.screenshot({path:path.join(evidence,'comparison-desktop.png')});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(evidence,'comparison-mobile.png')});await page.getByRole('button',{name:'关闭对话框',exact:true}).click();await page.setViewportSize({width:1280,height:900});
 await page.getByRole('button',{name:'加入我的原声开场',exact:true}).click();await page.locator('#intro-end').fill('2');await page.locator('#intro-phrase').fill('别急我在呢');await page.getByRole('button',{name:'确认本机拼接',exact:true}).click();await page.locator('#dialog-error').filter({hasText:'请确认'}).waitFor();results.push({check:'unconfirmed_voice_and_editing_rights_block_composition',passed:true});
 for(const key of ['heard_phrase_confirmed','voice_rights','processing_rights','share_voice','export_voice'])await page.locator('#intro-'+key).check();await page.screenshot({path:path.join(evidence,'intro-desktop.png')});await page.getByRole('button',{name:'确认本机拼接',exact:true}).click();await page.locator('#audio-panel').filter({hasText:'原声开场 2.00 秒'}).waitFor();
 const work=await page.evaluate(async wid=>fetch('/api/works/'+wid).then(r=>r.json()),seed.work_id),composed=work.audios.find(a=>a.kind==='voice_intro');assert.ok(composed);assert.ok(Math.abs(composed.duration-22.12)<.01);assert.equal(work.audios.length,3);
 const dataAudio=await page.evaluate(async id=>{const r=await fetch('/api/audio/'+id+'?download=1');return {status:r.status,mime:r.headers.get('content-type'),size:(await r.arrayBuffer()).byteLength};},composed.id);assert.equal(dataAudio.status,200);assert.match(dataAudio.mime,/wav/);assert.ok(dataAudio.size>100000);results.push({check:'native_voice_intro_full_song_wav_export',passed:true,source:'synthetic tones; no human phrase verification'});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(evidence,'creative-mobile.png'),fullPage:true});results.push({check:'mobile_layout_no_document_overflow',passed:true});
 const other=await browser.newContext(),op=await other.newPage();await op.goto(url);await op.locator('#story').waitFor();assert.equal(await op.evaluate(async wid=>(await fetch('/api/works/'+wid+'/comparison?line_id=x')).status,seed.work_id),404);results.push({check:'comparison_owner_isolation',passed:true});await other.close();
 assert.deepEqual(errors,[]);assert.equal(external,0);results.push({check:'no_external_requests_or_js_errors',passed:true});
 fs.writeFileSync(path.join(evidence,'creative-browser-results.json'),JSON.stringify({results,errors,external_requests:external,scope:'isolated_synthetic_fixture'},null,2)+'\n');console.log(JSON.stringify({passed:results.length,evidence}));
}finally{if(browser&&results.length<9){const p=browser.contexts()[0]?.pages()[0];if(p){console.error('Browser state:',(await p.locator('body').innerText()).slice(0,1800));console.error('JS errors:',errors);await p.screenshot({path:path.join(evidence,'failure.png')});}}if(browser)await browser.close();server.kill('SIGTERM');fs.rmSync(data,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
