const {chromium}=require('/Users/y/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core');
const {spawn,execFileSync}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),python='/Users/y/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
(async()=>{
 const data=fs.mkdtempSync(path.join(os.tmpdir(),'syp-diary-')),evidence=process.argv[2]||'/tmp/syp-diary-evidence';fs.mkdirSync(evidence,{recursive:true});
 const server=spawn(python,['-u','-c',"from server import make_server;from backend.providers import Gateway;import sys;s=make_server(0,sys.argv[1],Gateway());print(s.server_port,flush=True);s.serve_forever()",data],{cwd:root});
 const port=await new Promise((res,rej)=>{server.stdout.once('data',d=>res(Number(d.toString().trim())));server.once('exit',c=>rej(new Error('server '+c)));server.stderr.on('data',d=>process.stderr.write(d));});
 const url='http://127.0.0.1:'+port,results=[],errors=[];let browser,external=0;
 try{
  browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(url)&&!r.url().startsWith('blob:'))external++});page.on('dialog',d=>d.accept());
  await page.goto(url);await page.locator('#story').waitFor();const token=(await context.cookies()).find(c=>c.name==='syp_session').value;
  const seed=JSON.parse(execFileSync(python,['scripts/seed_creative.py'],{cwd:root,input:JSON.stringify({data_dir:data,session_token:token}),encoding:'utf8'}));
  await page.getByRole('button',{name:'声音日记',exact:true}).click();await page.locator('#diary-month').fill('2026-01');await page.getByRole('button',{name:'查看',exact:true}).click();await page.locator('.calendar-day').first().waitFor();assert.equal(await page.locator('.calendar-day').count(),31);
  async function add(day,phrase,link=false){await page.locator(`[data-action="diary-edit"][data-day="${day}"]`).first().click();await page.locator('#diary-phrase').fill(phrase);if(link)await page.locator('#diary-linked-work').selectOption(seed.work_id);await page.getByRole('button',{name:'保存这一天',exact:true}).click();await page.locator('.diary-entry').filter({hasText:phrase}).waitFor();await page.locator('#dialog').waitFor({state:'hidden'});}
  await add('2026-01-01','别急我在呢',true);await add('2026-01-02','今天终于见到你');results.push({check:'calendar_daily_save_and_existing_work_link',passed:true});
  const entry=page.locator('.diary-entry').filter({hasText:'别急我在呢'});assert.equal(await entry.locator('audio').count(),3);await entry.locator('audio').first().evaluate(a=>a.play());assert.equal(await entry.locator('audio').first().evaluate(a=>a.paused),false);results.push({check:'saved_story_voice_and_matching_formal_songs_play',passed:true,source:'synthetic tones'});
  await page.screenshot({path:path.join(evidence,'diary-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(evidence,'diary-mobile.png'),fullPage:true});results.push({check:'mobile_calendar_and_players_fit',passed:true});await page.setViewportSize({width:1280,height:900});
  await page.getByRole('button',{name:'用选中的原话创作',exact:true}).click();await page.locator('#page-error').filter({hasText:'请选择'}).waitFor();results.push({check:'selection_bounds_enforced_in_ui',passed:true});
  await page.locator('[data-diary-day="2026-01-01"]').check();await page.locator('[data-diary-day="2026-01-02"]').check();await page.getByRole('button',{name:'用选中的原话创作',exact:true}).click();await page.getByRole('button',{name:'创建并进入创作',exact:true}).click();await page.locator('#dialog-error').filter({hasText:'请先同意'}).waitFor();await page.locator('#diary-service-consent').check();await page.getByRole('button',{name:'创建并进入创作',exact:true}).click();await page.locator('#story').waitFor();assert.match(await page.locator('#story').inputValue(),/2026-01-01：别急我在呢/);results.push({check:'monthly_consent_then_exact_original_lyrics_creation',passed:true});
  await page.getByRole('button',{name:'声音日记',exact:true}).click();await page.locator('.diary-monthly').filter({hasText:'2026-01 · 这个月的我'}).waitFor();
  const csrf=await page.evaluate(()=>fetch('/api/session',{method:'POST'}).then(r=>r.json()).then(x=>x.csrf));
  const request=async(p,method='GET',body)=>page.evaluate(async({p,method,body,csrf})=>{const r=await fetch(p,{method,headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};},{p,method,body,csrf});
  const month=(await request('/api/diary?month=2026-01')).data;const mw=(await request('/api/works/'+month.monthly[0].id)).data;assert.equal(mw.jobs.length,0);assert.deepEqual(mw.lyrics[0].lines.map(l=>l.text),['别急我在呢','今天终于见到你']);assert.ok(mw.lyrics[0].lines.every(l=>l.locked));
  const selected=month.entries.map(e=>({day:e.day,base_version:e.version}));const duplicate=await request('/api/diary/monthly','POST',{month:'2026-01',entries:selected,service_consent:true});assert.equal(duplicate.data.id,mw.id);results.push({check:'monthly_snapshots_locked_no_model_calls_and_duplicate_safe',passed:true});
  assert.equal((await page.evaluate(async()=>{const r=await fetch('/api/diary/2026-01-03',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({phrase:'未授权',base_version:0})});return r.status;})),403);results.push({check:'mutation_without_csrf_rejected',passed:true});
  const other=await browser.newContext(),op=await other.newPage();await op.goto(url);await op.locator('#story').waitFor();const isolated=await op.evaluate(()=>fetch('/api/diary?month=2026-01').then(r=>r.json()));assert.equal(isolated.entries.length,0);assert.equal(isolated.monthly.length,0);assert.equal(await op.evaluate(async id=>(await fetch('/api/works/'+id)).status,mw.id),404);await other.close();results.push({check:'other_browser_identity_cannot_read_diary_or_monthly_work',passed:true});
  await page.locator('[data-action="diary-delete"][data-day="2026-01-02"]').click();await page.getByRole('button',{name:'删除日记',exact:true}).last().click();await page.locator('.diary-entry').filter({hasText:'今天终于见到你'}).waitFor({state:'hidden'});assert.equal((await request('/api/works/'+mw.id)).data.monthly_diary.sources.length,2);results.push({check:'delete_diary_keeps_explicit_monthly_snapshot',passed:true});
  await add('2026-01-03','今天慢慢走');await page.locator('[data-action="diary-work"][data-day="2026-01-03"]').click();await page.locator('#diary-service-consent').check();await page.getByRole('button',{name:'创建并进入创作',exact:true}).click();await page.locator('#story').waitFor();assert.equal(await page.locator('#story').inputValue(),'今天慢慢走');results.push({check:'daily_creation_uses_original_phrase_and_existing_recording_flow',passed:true});
  assert.deepEqual(errors,[]);assert.equal(external,0);results.push({check:'no_js_errors_or_external_requests',passed:true});fs.writeFileSync(path.join(evidence,'diary-browser-results.json'),JSON.stringify({results,errors,external_requests:external,scope:'isolated_synthetic_fixture'},null,2)+'\n');console.log(JSON.stringify({passed:results.length,evidence}));
 }finally{if(browser&&results.length<11){const p=browser.contexts()[0]?.pages()[0];if(p){console.error((await p.locator('body').innerText()).slice(0,2200));console.error(errors);await p.screenshot({path:path.join(evidence,'failure.png')});}}if(browser)await browser.close();server.kill('SIGTERM');fs.rmSync(data,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
