const {chromium}=require('/Users/y/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core');
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),python='/Users/y/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
(async()=>{
 const data=fs.mkdtempSync(path.join(os.tmpdir(),'syp-quick-')),evidence='/tmp/syp-quick-evidence';fs.mkdirSync(evidence,{recursive:true});
 const source="import sys;sys.path.insert(0,'tests');from test_providers import FakeGateway;from server import make_server;g=FakeGateway();g.lyric_result={'lines':[{'text':'别急我在呢'},{'text':'晚风陪我慢慢走'}]};s=make_server(0,sys.argv[1],g);print(s.server_port,flush=True);s.serve_forever()";
 const server=spawn(python,['-u','-c',source,data],{cwd:root}),port=await new Promise((res,rej)=>{server.stdout.once('data',d=>res(Number(d.toString().trim())));server.once('exit',c=>rej(new Error('server '+c)));server.stderr.on('data',d=>process.stderr.write(d));});
 const url='http://127.0.0.1:'+port,results=[],errors=[];let browser;
 try{
  browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.goto(url);await page.locator('#story').waitFor();await page.getByRole('button',{name:'试试三步简易版',exact:true}).click();assert.equal(await page.locator('[aria-current="step"]').innerText(),'1\n留一句话');assert.equal(await page.locator('#line-0').count(),0);assert.equal(await page.locator('#work-title').count(),0);results.push({check:'full_flow_retained_and_quick_step1_has_only_core_fields',passed:true});
  await page.getByRole('button',{name:'录音 / 上传原声',exact:true}).click();await page.locator('#clip-file').waitFor();assert.equal(await page.locator('#transcript').getAttribute('maxlength'),'80');await page.getByRole('button',{name:'关闭对话框',exact:true}).click();results.push({check:'existing_recording_and_upload_entry_available',passed:true});
  await page.locator('#story').fill('别急我在呢');await page.locator('#service-consent').check();await page.screenshot({path:path.join(evidence,'quick-story.png'),fullPage:true});await page.getByRole('button',{name:'生成短歌词 · 可能计费',exact:true}).click();await page.locator('#page-error').filter({hasText:'请确认'}).waitFor();assert.equal((await page.evaluate(()=>fetch('/api/works').then(r=>r.json()))).length,0);results.push({check:'unconfirmed_ai_request_does_not_create_or_generate',passed:true});
  await page.locator('#quick-paid-lyrics').check();await page.getByRole('button',{name:'生成短歌词 · 可能计费',exact:true}).click();await page.locator('#line-0').waitFor();assert.equal(await page.locator('#line-0').inputValue(),'别急我在呢');assert.equal(await page.locator('#story').count(),0);let works=await page.evaluate(()=>fetch('/api/works').then(r=>r.json()));assert.equal(works.length,1);let w=await page.evaluate(id=>fetch('/api/works/'+id).then(r=>r.json()),works[0].id);assert.equal(w.lyrics.length,0);assert.equal(w.intent.preserve,'别急我在呢');results.push({check:'ai_result_is_editable_unconfirmed_draft_and_original_is_preserved',passed:true});await page.screenshot({path:path.join(evidence,'quick-lyrics.png'),fullPage:true});
  await page.getByRole('button',{name:'确认歌词并生成歌曲',exact:true}).click();await page.locator('#page-error').filter({hasText:'请确认歌词'}).waitFor();w=await page.evaluate(id=>fetch('/api/works/'+id).then(r=>r.json()),w.id);assert.equal(w.jobs.length,0);assert.equal(w.lyrics.length,0);results.push({check:'song_requires_separate_explicit_paid_confirmation',passed:true});
  await page.locator('#line-1').fill('晚风陪我一起走');await page.locator('#quick-paid-song').check();await page.getByRole('button',{name:'确认歌词并生成歌曲',exact:true}).click();await page.locator('[aria-current="step"]').filter({hasText:'听我的歌'}).waitFor();await page.locator('#work-audio').waitFor({timeout:20000});w=await page.evaluate(id=>fetch('/api/works/'+id).then(r=>r.json()),w.id);assert.equal(w.lyrics.length,1);assert.equal(w.jobs.length,1);assert.equal(w.lyrics[0].lines[1].text,'晚风陪我一起走');assert.equal(w.audios.length,1);results.push({check:'single_cta_saves_lyrics_submits_one_job_and_polls_to_audio',passed:true,source:'FakeGateway synthetic audio'});
  await page.locator('#work-audio').evaluate(a=>a.play());assert.equal(await page.locator('#work-audio').evaluate(a=>a.paused),false);await page.screenshot({path:path.join(evidence,'quick-desktop.png')});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(evidence,'quick-mobile.png'),fullPage:true});await page.getByRole('button',{name:'保留这首歌',exact:true}).click();await page.getByRole('button',{name:'已保留',exact:true}).waitFor();results.push({check:'playback_and_mobile_layout',passed:true});
  await page.getByRole('button',{name:'打开完整工作室',exact:true}).click();await page.locator('#story').waitFor();assert.equal(await page.locator('#story').inputValue(),'别急我在呢');assert.equal(await page.locator('#work-title').count(),1);await page.reload();await page.locator('#story').waitFor();await page.getByRole('button',{name:'继续上次简易体验',exact:true}).click();await page.locator('#work-audio').waitFor();works=await page.evaluate(()=>fetch('/api/works').then(r=>r.json()));assert.equal(works.length,1);results.push({check:'full_flow_switch_and_reload_resume_keep_same_work_without_generation',passed:true});
  // Test actual private-candidate UI using the existing owner job, with only HTTP status presentation controlled.
  await page.route('**/api/works/'+w.id,async route=>{const response=await route.fetch(),body=await response.json();body.audios=[];body.jobs[0].status='checking';body.jobs[0].preview_ready=true;await route.fulfill({response,json:body});});
  await page.getByRole('button',{name:'刷新实际结果',exact:true}).click();await page.locator('.quick-details summary').waitFor();assert.equal(await page.locator('[data-action="review-audio"]').isVisible(),false);await page.locator('.quick-details summary').click();assert.equal(await page.locator('[data-action="review-audio"]').isVisible(),true);results.push({check:'private_preview_is_labeled_and_full_review_requires_expansion',passed:true,method:'controlled presentation; no real candidate audit'});await page.unroute('**/api/works/'+w.id);
  const offline=await browser.newContext(),off=await offline.newPage();off.on('pageerror',e=>errors.push(e.message));await off.route('**/api/capabilities',async route=>{const r=await route.fetch(),b=await r.json();b.lyrics=false;b.singing=false;await route.fulfill({response:r,json:b});});await off.goto(url);await off.locator('#story').waitFor();await off.getByRole('button',{name:'试试三步简易版',exact:true}).click();await off.locator('#story').fill('今天慢慢走');await off.locator('#service-consent').check();await off.getByRole('button',{name:'下一步 · 我自己写两句',exact:true}).click();await off.locator('#line-1').fill('晚风陪我回家');await off.getByRole('button',{name:'只保存歌词，暂不生成',exact:true}).click();await off.locator('#quick-result').filter({hasText:'歌词已保存'}).waitFor();const offlineWorks=await off.evaluate(()=>fetch('/api/works').then(r=>r.json()));assert.equal(offlineWorks.length,1);const ow=await off.evaluate(id=>fetch('/api/works/'+id).then(r=>r.json()),offlineWorks[0].id);assert.equal(ow.jobs.length,0);assert.equal(ow.lyrics.length,1);await offline.close();results.push({check:'no_provider_manual_path_saves_without_generating',passed:true});
  await page.getByRole('button',{name:'打开完整工作室',exact:true}).click();await page.getByRole('button',{name:'写一首',exact:true}).count();await page.getByRole('button',{name:'我的小歌',exact:true}).click();await page.getByRole('button',{name:'写一首',exact:true}).click();await page.getByRole('button',{name:'试试三步简易版',exact:true}).click();await page.locator('#story').fill('别急我在呢');await page.locator('#service-consent').check();await page.locator('#quick-paid-lyrics').check();await page.route('**/lyrics/generate',route=>route.abort());await page.getByRole('button',{name:'生成短歌词 · 可能计费',exact:true}).click();await page.locator('#page-error').filter({hasText:'无法连接'}).waitFor();assert.equal(await page.locator('#story').inputValue(),'别急我在呢');works=await page.evaluate(()=>fetch('/api/works').then(r=>r.json()));assert.equal(works.length,2);await page.unroute('**/lyrics/generate');results.push({check:'uncertain_lyrics_failure_retains_story_and_created_work',passed:true});
  assert.deepEqual(errors,[]);results.push({check:'no_javascript_errors',passed:true});fs.writeFileSync(path.join(evidence,'quick-browser-results.json'),JSON.stringify({results,errors,external_model_calls:0,scope:'isolated_FakeGateway'},null,2)+'\n');console.log(JSON.stringify({passed:results.length,evidence}));
 }finally{if(browser&&results.length<10){const p=browser.contexts()[0]?.pages()[0];if(p){console.error((await p.locator('body').innerText()).slice(0,2200));console.error(errors);await p.screenshot({path:path.join(evidence,'failure.png')});}}if(browser)await browser.close();server.kill('SIGTERM');fs.rmSync(data,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
